# Test with
# ansible -i inventory.yml all --list-hosts
#
# see https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html
# see https://docs.ansible.com/ansible/latest/plugins/inventory/yaml.html
all:
  children:
    group_cloud_dfir_laboratory:
      hosts:
        laboratory-dev:
          ansible_port: 2222
          ansible_host: 127.0.0.1
          ansible_user: vagrant
          ansible_ssh_private_key_file: /home/artem/Desktop/vagrant/.vagrant/machines/default/virtualbox/private_key
          ansible_python_interpreter: /usr/bin/python3
          ansible_become_method: sudo
