version: '3'
services:
  logcollector:
    environment:
      - TIMESKETCH_ADDRESS=http://timesketch:80
    ports:
      - "127.0.0.1:9000:9000"
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    depends_on:
      - timesketch
    restart: always

  timesketch:
    image: temach/cloud-dfir-timesketch
    environment:
      - POSTGRES_USER=timesketch
      - POSTGRES_PASSWORD=password
      - POSTGRES_ADDRESS=postgres
      - POSTGRES_PORT=5432
      - ELASTIC_ADDRESS=elasticsearch
      - ELASTIC_PORT=9200
      - REDIS_ADDRESS=redis
      - REDIS_PORT=6379
      - TIMESKETCH_USER=admin
      - TIMESKETCH_PASSWORD=admin
    ports:
      - "127.0.0.1:80:80"
    depends_on:
      - elasticsearch
      - postgres
      - redis
    restart: always

  elasticsearch:
    environment:
      - TAKE_FILE_OWNERSHIP=1
      - discovery.type=single-node
    # uncomment the following lines to control JVM memory utilization
    # in smaller deployments with minimal resources
    #  - ES_JAVA_OPTS= -Xms1g -Xmx1g # 1G min/1G max
    image: elasticsearch:7.6.2
#    ports:
#      - "9200:9200"
#      - "9300:9300"
    restart: always

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=timesketch
      - POSTGRES_PASSWORD=password
    restart: always

  redis:
    image: redis
    restart: always
